package com.archeo.server.modules.common.enums;

public enum Resource {
    USER_PROFILE,
    USER_SETTINGS,
    USER_ACTIVITY_LOG,
    NOTIF,
    CONTACT,
    SIGNATURE,
    DASHBOARD,

    DOCUMENT,
    DOCUMENT_METADATA,
    DOCUMENT_VERSION_AUDIT,
    DOCUMENT_ACCESS_AUDIT,
    DOCUMENT_BULK,
    DOCUMENT_BULK_SHARED,
    DOCUMENT_SHARED_AUDIT_ALL,
    DOCUMENT_SHARED_AUDIT_VERSION,
    DOCUMENT_SHARED_AUDIT_ACCESS,

    TEMPLATE,
    TEMPLATE_VERSION_HISTORY,
    TEMPLATE_BULK,
    TEMPLATE_AUDIT,
    DATA_TABLE,

    DOMAIN,
    API_CONFIG,
    API_KEY,
    API_USAGE,
    API,
    PROFILE,
    PROFILE_AUDIT,
    SETTINGS,
    API_AUDIT
}
